version: "3"
services:
    nginx:
        image: nginx:1.17.10
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - /static:/static
        depends_on:
            - web

    web:
        build: .
        command: bash -c "
            python manage.py collectstatic --no-input &&
            python manage.py makemigrations && 
            python manage.py migrate && 
            gunicorn project.wsgi:application -b 0:8080"
        depends_on:
            - db
        volumes:
            - ./src:/src
            - /static:/static

    db:
        image: postgres:12.2
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin